[package]
name = "huak-rewrite"
version = "0.1.0"
edition = "2021"

[lib]
name = "huak"
path = "./src/huak/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
